//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.Crededit
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.cbr.ru/", ConfigurationName="CBR.Crededit.CreditOrgInfoSoap")]
    public interface CreditOrgInfoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> CreditInfoByIntCodeAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetAgency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetAgencyAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetAgencyXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgencyXMLAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetFBU", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetFBUAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetRiskFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetRiskFilesAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetRiskFilesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetRiskFilesXMLAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetFBUXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFBUXMLAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOffices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetOfficesAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesByRegion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetOfficesByRegionAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesXMLAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesByRegionXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesByRegionXMLAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134FormFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data134FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Olap134Form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Olap134FormAsync(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135FormFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data135FormFullAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135MetaFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data135MetaFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135MetaFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data135MetaFullAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135FormFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data135FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123FormFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data123FormFullAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123FormFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data123FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF123", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF123Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF101", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF101Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF102", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF102Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF134", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF134Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF135", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF135Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134FormFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data134FormFullAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetProfit97", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> GetProfit97Async(int nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetBalance97", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> GetBalance97Async(int nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetProfit98", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> GetProfit98Async(int regnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetBalance98", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> GetBalance98Async(int regnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetBalanceAsync(int regnum, int when, string show);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetAnnual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnualAsync(int regnum, int when, string show);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetAnnual2015", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnual2015Async(int regnum, int when, string show);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetAnnual2016", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnual2016Async(int regnum, int when, string show);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetAnnual2017", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnual2017Async(int regnum, int when, string show);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF805Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF805DataAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF805Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF805XmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data802FXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data802FXMLAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data802F", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data802FAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data803FXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data803FXMLAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data803F", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data803FAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF806Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF806XmlAsync(int CredorgNumber, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF806Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF806DataAsync(int CredorgNumber, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF807Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF807XmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF807Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF807DataAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF808Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF808XmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF808Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF808DataAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF808BGXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF808BGXmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF808BGData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF808BGDataAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF810Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF810XmlAsync(int CredorgNumber, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF810Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF810DataAsync(int CredorgNumber, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF813Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF813DataAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF813Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813XmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF813MXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813MXmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF813BGData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF813BGDataAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF813BGXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813BGXmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF813BGMXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813BGMXmlAsync(int CredorgNumber, System.DateTime dateTime, int par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF814Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetF814XmlAsync(int CredorgNumber, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetF814Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF814DataAsync(int CredorgNumber, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumBIC_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EnumBIC_XMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetFormsMaxDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime> GetFormsMaxDateAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumRegions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> EnumRegionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumRegionsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EnumRegionsXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LastUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.DateTime> LastUpdateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumBIC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> EnumBICAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FormExXMLAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FormExAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullXMLAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FOldXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FOldXMLAsync(int when);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FOld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FOldAsync(int when);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134bFXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data134bFXMLAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134bF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data134bFAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123bFXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data123bFXMLAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123bF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data123bFAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FNewXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FNewXMLAsync(int CredorgNumber, System.DateTime Dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FNewAsync(int CredorgNumber, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101Form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FormAsync(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExXMLAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullExAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExV2XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExV2XMLAsync(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullExV2Async(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101Full", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullV2XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullV2XMLAsync(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullV2Async(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByRegCodeShort", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> CreditInfoByRegCodeShortAsync(int CredorgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByRegCodeShortXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByRegCodeShortXMLAsync(int CredorgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormExXMLAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FormExAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FXMLAsync(int CredorgNumber, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102F", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FAsync(int CredorgNumber, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FoldXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FoldXMLAsync(int when);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102Fold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FoldAsync(int when);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormXMLAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102Form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FormAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form102IndicatorsEnumXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Form102IndicatorsEnumXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form102IndicatorsEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Form102IndicatorsEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form101IndicatorsEnumXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Form101IndicatorsEnumXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form101IndicatorsEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Form101IndicatorsEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegNumToIntCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<double> RegNumToIntCodeAsync(double RegNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IntCodeToRegNumStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> IntCodeToRegNumStrAsync(double IntNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IntCodeToRegNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<double> IntCodeToRegNumAsync(double IntNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToIntCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<double> BicToIntCodeAsync(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToRegNumberStr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> BicToRegNumberStrAsync(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToRegNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<int> BicToRegNumberAsync(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegionsEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> RegionsEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegionsEnumXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RegionsEnumXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearcBranchesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SearcBranchesXMLAsync(string name, string rgn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearcBranches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearcBranchesAsync(string name, string rgn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByRegionCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearchByRegionCodeAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByRegionCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByRegionCodeXMLAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByNameXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByNameXMLAsync(string NamePart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumLicenses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> EnumLicensesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumLicensesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EnumLicensesXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearchByNameAsync(string NamePart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByNameExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByNameExXMLAsync(string NamePart, string rgn, string nsitype, string status, short[] license, bool fo, bool cards, bool fshare, bool jstock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByNameEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearchByNameExAsync(string NamePart, string rgn, string nsitype, string status, short[] license, bool fo, bool cards, bool fshare, bool jstock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeXMLAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GeCardsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GeCardsXMLAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GeCards", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GeCardsAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetSitesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetSitesXMLAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetSites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetSitesAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetSitesFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetSitesFullXMLAsync(string name, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetSitesFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetSitesFullAsync(string name, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeExXMLAsync(double[] InternalCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> CreditInfoByIntCodeExAsync(double[] InternalCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetPeriodsOfDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetPeriodsOfDocumentsAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetBankrotsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetBankrotsXMLAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetBankrots", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetBankrotsAsync(double InternalCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.cbr.ru/")]
    public partial class ResBalance
    {
        
        private string titleField;
        
        private string hTMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HTML
        {
            get
            {
                return this.hTMLField;
            }
            set
            {
                this.hTMLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface CreditOrgInfoSoapChannel : CBR.Crededit.CreditOrgInfoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CreditOrgInfoSoapClient : System.ServiceModel.ClientBase<CBR.Crededit.CreditOrgInfoSoap>, CBR.Crededit.CreditOrgInfoSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreditOrgInfoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CreditOrgInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), CreditOrgInfoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditOrgInfoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreditOrgInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditOrgInfoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreditOrgInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditOrgInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> CreditInfoByIntCodeAsync(double InternalCode)
        {
            return base.Channel.CreditInfoByIntCodeAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetAgencyAsync(double IntCode)
        {
            return base.Channel.GetAgencyAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgencyXMLAsync(double IntCode)
        {
            return base.Channel.GetAgencyXMLAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetFBUAsync(double IntCode)
        {
            return base.Channel.GetFBUAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetRiskFilesAsync(double IntCode)
        {
            return base.Channel.GetRiskFilesAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetRiskFilesXMLAsync(double IntCode)
        {
            return base.Channel.GetRiskFilesXMLAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFBUXMLAsync(double IntCode)
        {
            return base.Channel.GetFBUXMLAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetOfficesAsync(double IntCode)
        {
            return base.Channel.GetOfficesAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetOfficesByRegionAsync(int RegCode)
        {
            return base.Channel.GetOfficesByRegionAsync(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesXMLAsync(double IntCode)
        {
            return base.Channel.GetOfficesXMLAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesByRegionXMLAsync(int RegCode)
        {
            return base.Channel.GetOfficesByRegionXMLAsync(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data134FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data134FormFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Olap134FormAsync(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate)
        {
            return base.Channel.Olap134FormAsync(Code, CredorgNumber, FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data135FormFullAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data135FormFullAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data135MetaFullXMLAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data135MetaFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data135MetaFullAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data135MetaFullAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data135FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data135FormFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data123FormFullAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data123FormFullAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data123FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data123FormFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF123Async(int CredprgNumber)
        {
            return base.Channel.GetDatesForF123Async(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF101Async(int CredprgNumber)
        {
            return base.Channel.GetDatesForF101Async(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF102Async(int CredprgNumber)
        {
            return base.Channel.GetDatesForF102Async(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF134Async(int CredprgNumber)
        {
            return base.Channel.GetDatesForF134Async(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF135Async(int CredprgNumber)
        {
            return base.Channel.GetDatesForF135Async(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data134FormFullAsync(int CredorgNumber, System.DateTime OnDate)
        {
            return base.Channel.Data134FormFullAsync(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<string> GetProfit97Async(int nom)
        {
            return base.Channel.GetProfit97Async(nom);
        }
        
        public System.Threading.Tasks.Task<string> GetBalance97Async(int nom)
        {
            return base.Channel.GetBalance97Async(nom);
        }
        
        public System.Threading.Tasks.Task<string> GetProfit98Async(int regnum)
        {
            return base.Channel.GetProfit98Async(regnum);
        }
        
        public System.Threading.Tasks.Task<string> GetBalance98Async(int regnum)
        {
            return base.Channel.GetBalance98Async(regnum);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetBalanceAsync(int regnum, int when, string show)
        {
            return base.Channel.GetBalanceAsync(regnum, when, show);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnualAsync(int regnum, int when, string show)
        {
            return base.Channel.GetAnnualAsync(regnum, when, show);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnual2015Async(int regnum, int when, string show)
        {
            return base.Channel.GetAnnual2015Async(regnum, when, show);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnual2016Async(int regnum, int when, string show)
        {
            return base.Channel.GetAnnual2016Async(regnum, when, show);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ResBalance> GetAnnual2017Async(int regnum, int when, string show)
        {
            return base.Channel.GetAnnual2017Async(regnum, when, show);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF805DataAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF805DataAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF805XmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF805XmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data802FXMLAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data802FXMLAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data802FAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data802FAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data803FXMLAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data803FXMLAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data803FAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data803FAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF806XmlAsync(int CredorgNumber, System.DateTime dateTime)
        {
            return base.Channel.GetF806XmlAsync(CredorgNumber, dateTime);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF806DataAsync(int CredorgNumber, System.DateTime dateTime)
        {
            return base.Channel.GetF806DataAsync(CredorgNumber, dateTime);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF807XmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF807XmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF807DataAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF807DataAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF808XmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF808XmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF808DataAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF808DataAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF808BGXmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF808BGXmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF808BGDataAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF808BGDataAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF810XmlAsync(int CredorgNumber, System.DateTime dateTime)
        {
            return base.Channel.GetF810XmlAsync(CredorgNumber, dateTime);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF810DataAsync(int CredorgNumber, System.DateTime dateTime)
        {
            return base.Channel.GetF810DataAsync(CredorgNumber, dateTime);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF813DataAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF813DataAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813XmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF813XmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813MXmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF813MXmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF813BGDataAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF813BGDataAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813BGXmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF813BGXmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF813BGMXmlAsync(int CredorgNumber, System.DateTime dateTime, int par)
        {
            return base.Channel.GetF813BGMXmlAsync(CredorgNumber, dateTime, par);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetF814XmlAsync(int CredorgNumber, System.DateTime dateTime)
        {
            return base.Channel.GetF814XmlAsync(CredorgNumber, dateTime);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetF814DataAsync(int CredorgNumber, System.DateTime dateTime)
        {
            return base.Channel.GetF814DataAsync(CredorgNumber, dateTime);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EnumBIC_XMLAsync()
        {
            return base.Channel.EnumBIC_XMLAsync();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetFormsMaxDateAsync(int code)
        {
            return base.Channel.GetFormsMaxDateAsync(code);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> EnumRegionsAsync()
        {
            return base.Channel.EnumRegionsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EnumRegionsXMLAsync()
        {
            return base.Channel.EnumRegionsXMLAsync();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> LastUpdateAsync()
        {
            return base.Channel.LastUpdateAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> EnumBICAsync()
        {
            return base.Channel.EnumBICAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FormExXMLAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FormExXMLAsync(CredorgNumbers, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FormExAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FormExAsync(CredorgNumbers, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullXMLAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullXMLAsync(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FOldXMLAsync(int when)
        {
            return base.Channel.Data101FOldXMLAsync(when);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FOldAsync(int when)
        {
            return base.Channel.Data101FOldAsync(when);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data134bFXMLAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data134bFXMLAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data134bFAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data134bFAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data123bFXMLAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data123bFXMLAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data123bFAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data123bFAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FNewXMLAsync(int CredorgNumber, System.DateTime Dt)
        {
            return base.Channel.Data101FNewXMLAsync(CredorgNumber, Dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FNewAsync(int CredorgNumber, System.DateTime dt)
        {
            return base.Channel.Data101FNewAsync(CredorgNumber, dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FormAsync(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FormAsync(CredorgNumber, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExXMLAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullExXMLAsync(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullExAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullExAsync(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExV2XMLAsync(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullExV2XMLAsync(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullExV2Async(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullExV2Async(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullAsync(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullV2XMLAsync(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullV2XMLAsync(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data101FullV2Async(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data101FullV2Async(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> CreditInfoByRegCodeShortAsync(int CredorgNumber)
        {
            return base.Channel.CreditInfoByRegCodeShortAsync(CredorgNumber);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByRegCodeShortXMLAsync(int CredorgNumber)
        {
            return base.Channel.CreditInfoByRegCodeShortXMLAsync(CredorgNumber);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormExXMLAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data102FormExXMLAsync(CredorgNumbers, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FormExAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data102FormExAsync(CredorgNumbers, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FXMLAsync(int CredorgNumber, System.DateTime dt)
        {
            return base.Channel.Data102FXMLAsync(CredorgNumber, dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FAsync(int CredorgNumber, System.DateTime dt)
        {
            return base.Channel.Data102FAsync(CredorgNumber, dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FoldXMLAsync(int when)
        {
            return base.Channel.Data102FoldXMLAsync(when);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FoldAsync(int when)
        {
            return base.Channel.Data102FoldAsync(when);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormXMLAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data102FormXMLAsync(CredorgNumber, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Data102FormAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Data102FormAsync(CredorgNumber, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Form102IndicatorsEnumXMLAsync()
        {
            return base.Channel.Form102IndicatorsEnumXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Form102IndicatorsEnumAsync()
        {
            return base.Channel.Form102IndicatorsEnumAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Form101IndicatorsEnumXMLAsync()
        {
            return base.Channel.Form101IndicatorsEnumXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> Form101IndicatorsEnumAsync()
        {
            return base.Channel.Form101IndicatorsEnumAsync();
        }
        
        public System.Threading.Tasks.Task<double> RegNumToIntCodeAsync(double RegNumber)
        {
            return base.Channel.RegNumToIntCodeAsync(RegNumber);
        }
        
        public System.Threading.Tasks.Task<string> IntCodeToRegNumStrAsync(double IntNumber)
        {
            return base.Channel.IntCodeToRegNumStrAsync(IntNumber);
        }
        
        public System.Threading.Tasks.Task<double> IntCodeToRegNumAsync(double IntNumber)
        {
            return base.Channel.IntCodeToRegNumAsync(IntNumber);
        }
        
        public System.Threading.Tasks.Task<double> BicToIntCodeAsync(string BicCode)
        {
            return base.Channel.BicToIntCodeAsync(BicCode);
        }
        
        public System.Threading.Tasks.Task<string> BicToRegNumberStrAsync(string BicCode)
        {
            return base.Channel.BicToRegNumberStrAsync(BicCode);
        }
        
        public System.Threading.Tasks.Task<int> BicToRegNumberAsync(string BicCode)
        {
            return base.Channel.BicToRegNumberAsync(BicCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> RegionsEnumAsync()
        {
            return base.Channel.RegionsEnumAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RegionsEnumXMLAsync()
        {
            return base.Channel.RegionsEnumXMLAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SearcBranchesXMLAsync(string name, string rgn)
        {
            return base.Channel.SearcBranchesXMLAsync(name, rgn);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearcBranchesAsync(string name, string rgn)
        {
            return base.Channel.SearcBranchesAsync(name, rgn);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearchByRegionCodeAsync(int RegCode)
        {
            return base.Channel.SearchByRegionCodeAsync(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByRegionCodeXMLAsync(int RegCode)
        {
            return base.Channel.SearchByRegionCodeXMLAsync(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByNameXMLAsync(string NamePart)
        {
            return base.Channel.SearchByNameXMLAsync(NamePart);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> EnumLicensesAsync()
        {
            return base.Channel.EnumLicensesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EnumLicensesXMLAsync()
        {
            return base.Channel.EnumLicensesXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearchByNameAsync(string NamePart)
        {
            return base.Channel.SearchByNameAsync(NamePart);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByNameExXMLAsync(string NamePart, string rgn, string nsitype, string status, short[] license, bool fo, bool cards, bool fshare, bool jstock)
        {
            return base.Channel.SearchByNameExXMLAsync(NamePart, rgn, nsitype, status, license, fo, cards, fshare, jstock);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> SearchByNameExAsync(string NamePart, string rgn, string nsitype, string status, short[] license, bool fo, bool cards, bool fshare, bool jstock)
        {
            return base.Channel.SearchByNameExAsync(NamePart, rgn, nsitype, status, license, fo, cards, fshare, jstock);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeXMLAsync(double InternalCode)
        {
            return base.Channel.CreditInfoByIntCodeXMLAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GeCardsXMLAsync(double InternalCode)
        {
            return base.Channel.GeCardsXMLAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GeCardsAsync(double InternalCode)
        {
            return base.Channel.GeCardsAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetSitesXMLAsync(double InternalCode)
        {
            return base.Channel.GetSitesXMLAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetSitesAsync(double InternalCode)
        {
            return base.Channel.GetSitesAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetSitesFullXMLAsync(string name, string url)
        {
            return base.Channel.GetSitesFullXMLAsync(name, url);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetSitesFullAsync(string name, string url)
        {
            return base.Channel.GetSitesFullAsync(name, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeExXMLAsync(double[] InternalCodes)
        {
            return base.Channel.CreditInfoByIntCodeExXMLAsync(InternalCodes);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> CreditInfoByIntCodeExAsync(double[] InternalCodes)
        {
            return base.Channel.CreditInfoByIntCodeExAsync(InternalCodes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetPeriodsOfDocumentsAsync(double InternalCode)
        {
            return base.Channel.GetPeriodsOfDocumentsAsync(InternalCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetBankrotsXMLAsync(double IntCode)
        {
            return base.Channel.GetBankrotsXMLAsync(IntCode);
        }
        
        public System.Threading.Tasks.Task<CBR.Crededit.ArrayOfXElement> GetBankrotsAsync(double InternalCode)
        {
            return base.Channel.GetBankrotsAsync(InternalCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditOrgInfoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditOrgInfoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditOrgInfoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cbr.ru/CreditInfoWebServ/CreditOrgInfo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditOrgInfoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cbr.ru/CreditInfoWebServ/CreditOrgInfo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CreditOrgInfoSoap,
            
            CreditOrgInfoSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
