//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.Sec
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.cbr.ru/", ConfigurationName="CBR.Sec.SecInfoSoap")]
    public interface SecInfoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CouponsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CouponsXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CouponsMaxMin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CouponsMaxMinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/AuctionsBMR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> AuctionsBMRAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/AuctionsBMRXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AuctionsBMRXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/AuctionsMBRMaxMin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AuctionsMBRMaxMinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GKOOFZ_Analit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GKOOFZ_AnalitAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GKOOFZ_AnalitXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GKOOFZ_AnalitXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GKOOFZ_Exchinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GKOOFZ_ExchinfoAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GKOOFZ_ExchinfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GKOOFZ_ExchinfoXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Auctions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> AuctionsAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/AuctionsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AuctionsXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/UnSecLoans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> UnSecLoansAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/UnSecLoansXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UnSecLoansXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RepoSessionXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RepoSessionXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RepoSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RepoSessionAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Lombard_MinprocXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Lombard_MinprocXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Lombard_Minproc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Lombard_MinprocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Minrates_CAXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Minrates_CAXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Minrates_CA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Minrates_CAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DepoMaxProcXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DepoMaxProcXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DepoMaxProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> DepoMaxProcAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_1_3W", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_1_3WAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_1_3WXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_1_3WXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_3MXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_3MXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_3M", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_3MAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_12MXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_12MXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_12M", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_12MAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_18MXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_18MXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RatesCA_18M", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_18MAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Sp_fxpm_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Sp_fxpm_XMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketCredit_1D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketCredit_1DAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Avgprocstav", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> AvgprocstavAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/AvgprocstavXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AvgprocstavXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketCredit_1DXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketCredit_1DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketCredit_365D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketCredit_365DAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketCredit_365DXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketCredit_365DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Loansgold_1D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Loansgold_1DAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Loansgold_1DXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Loansgold_1DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Loansgold_365D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Loansgold_365DAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Loansgold_365DXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Loansgold_365DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/creditco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> creditcoAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/depf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> depfAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/depfNewXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> depfNewXMLAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/depfNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> depfNewAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Stav1w", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Stav1wAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Thin_adj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Thin_adjAsync(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MBXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> MBXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRplacementInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OBRplacementInfoXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRplacementInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRplacementInfoAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRplacmentResultInfoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OBRplacmentResultInfoXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRplacmentResultInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRplacmentResultInfoAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRVolumeInCircXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OBRVolumeInCircXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRVolumeInCirc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRVolumeInCircAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BliquidityXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> BliquidityXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Bliquidity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> BliquidityAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NFEA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NFEAAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/VKO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> VKOAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/VKOXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> VKOXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OpenMarket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OpenMarketAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OpenMarketXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OpenMarketXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SecLoansDebtXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SecLoansDebtXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SecLoansDebt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> SecLoansDebtAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> MBAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Flikvid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FlikvidAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FlikvidXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> FlikvidXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LoansGoldXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> LoansGoldXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LoansGold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> LoansGoldAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DirRepoAuctionParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> DirRepoAuctionParamAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/DirRepoAuctionParamXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DirRepoAuctionParamXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LombardListDates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> LombardListDatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LombardList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> LombardListAsync(string dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GCurveParams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GCurveParamsAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Isoterm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IsotermAsync(System.DateTime OnDate, System.DateTime ToDate, int I_Day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GCurve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GCurveAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketCreditXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketCreditXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketCreditAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketAuctionParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketAuctionParamAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketAuctionParamXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketAuctionParamXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketAuctionResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketAuctionResultsAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/NonMarketAuctionResultsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketAuctionResultsXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard3mXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard3mXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard6mXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard6mXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard1wXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard1wXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard2wXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard2wXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard12mXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard12mXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard3m", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard3mAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard6m", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard6mAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard12m", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard12mAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard1w", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard1wAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/rates_lombard2w", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard2wAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixedStav1DayXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> FixedStav1DayXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixedStav7DayXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> FixedStav7DayXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixedStav30DayXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> FixedStav30DayXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixedStav30Day", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FixedStav30DayAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixedStav7Day", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FixedStav7DayAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/FixedStav1Day", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FixedStav1DayAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/ItogiDepoAuctXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ItogiDepoAuctXMLAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/ItogiDepoAuct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> ItogiDepoAuctAsync(System.DateTime OnDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IDRepoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IDRepoXMLAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IDRepo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IDRepoAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IDRepoRUBXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IDRepoRUBXMLAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IDRepoRUB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IDRepoRUBAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IDRepoUSDXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IDRepoUSDXMLAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IDRepoUSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IDRepoUSDAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IBMRepo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IBMRepoAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IBMRepoXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IBMRepoXMLAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GKOOFZ_MR_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GKOOFZ_MR_XMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GKOOFZ_MR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GKOOFZ_MRAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Repo_sheduleFX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Repo_sheduleFXAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/REPOFXXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> REPOFXXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/REPOFX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> REPOFXAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/REPOXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> REPOXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/REPO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> REPOAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBRXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> OBRXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/OBR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MosPrimeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> MosPrimeXMLAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/MosPrime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> MosPrimeAsync(System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BankPapersXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> BankPapersXMLAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BankPapers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> BankPapersAsync(System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Coupons", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> CouponsAsync(System.DateTime DateFrom, System.DateTime DateTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SecInfoSoapChannel : CBR.Sec.SecInfoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SecInfoSoapClient : System.ServiceModel.ClientBase<CBR.Sec.SecInfoSoap>, CBR.Sec.SecInfoSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecInfoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SecInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), SecInfoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecInfoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecInfoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecInfoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CouponsXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.CouponsXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CouponsMaxMinAsync()
        {
            return base.Channel.CouponsMaxMinAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> AuctionsBMRAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.AuctionsBMRAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AuctionsBMRXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.AuctionsBMRXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AuctionsMBRMaxMinAsync()
        {
            return base.Channel.AuctionsMBRMaxMinAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GKOOFZ_AnalitAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.GKOOFZ_AnalitAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GKOOFZ_AnalitXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.GKOOFZ_AnalitXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GKOOFZ_ExchinfoAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.GKOOFZ_ExchinfoAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GKOOFZ_ExchinfoXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.GKOOFZ_ExchinfoXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> AuctionsAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.AuctionsAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AuctionsXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.AuctionsXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> UnSecLoansAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.UnSecLoansAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UnSecLoansXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.UnSecLoansXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RepoSessionXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.RepoSessionXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RepoSessionAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.RepoSessionAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Lombard_MinprocXMLAsync()
        {
            return base.Channel.Lombard_MinprocXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Lombard_MinprocAsync()
        {
            return base.Channel.Lombard_MinprocAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Minrates_CAXMLAsync()
        {
            return base.Channel.Minrates_CAXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Minrates_CAAsync()
        {
            return base.Channel.Minrates_CAAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DepoMaxProcXMLAsync()
        {
            return base.Channel.DepoMaxProcXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> DepoMaxProcAsync()
        {
            return base.Channel.DepoMaxProcAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_1_3WAsync()
        {
            return base.Channel.RatesCA_1_3WAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_1_3WXMLAsync()
        {
            return base.Channel.RatesCA_1_3WXMLAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_3MXMLAsync()
        {
            return base.Channel.RatesCA_3MXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_3MAsync()
        {
            return base.Channel.RatesCA_3MAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_12MXMLAsync()
        {
            return base.Channel.RatesCA_12MXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_12MAsync()
        {
            return base.Channel.RatesCA_12MAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RatesCA_18MXMLAsync()
        {
            return base.Channel.RatesCA_18MXMLAsync();
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> RatesCA_18MAsync()
        {
            return base.Channel.RatesCA_18MAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Sp_fxpm_XMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Sp_fxpm_XMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketCredit_1DAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.NonMarketCredit_1DAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> AvgprocstavAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.AvgprocstavAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AvgprocstavXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.AvgprocstavXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketCredit_1DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.NonMarketCredit_1DXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketCredit_365DAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.NonMarketCredit_365DAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketCredit_365DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.NonMarketCredit_365DXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Loansgold_1DAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Loansgold_1DAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Loansgold_1DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Loansgold_1DXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> Loansgold_365DAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Loansgold_365DAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Loansgold_365DXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Loansgold_365DXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> creditcoAsync(System.DateTime dt)
        {
            return base.Channel.creditcoAsync(dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> depfAsync(System.DateTime dt)
        {
            return base.Channel.depfAsync(dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> depfNewXMLAsync(System.DateTime dt)
        {
            return base.Channel.depfNewXMLAsync(dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> depfNewAsync(System.DateTime dt)
        {
            return base.Channel.depfNewAsync(dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Stav1wAsync(System.DateTime dt)
        {
            return base.Channel.Stav1wAsync(dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Thin_adjAsync(System.DateTime dt)
        {
            return base.Channel.Thin_adjAsync(dt);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> MBXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.MBXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OBRplacementInfoXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.OBRplacementInfoXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRplacementInfoAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.OBRplacementInfoAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OBRplacmentResultInfoXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.OBRplacmentResultInfoXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRplacmentResultInfoAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.OBRplacmentResultInfoAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OBRVolumeInCircXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.OBRVolumeInCircXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRVolumeInCircAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.OBRVolumeInCircAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> BliquidityXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.BliquidityXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> BliquidityAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.BliquidityAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NFEAAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.NFEAAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> VKOAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.VKOAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> VKOXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.VKOXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OpenMarketAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.OpenMarketAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OpenMarketXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.OpenMarketXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SecLoansDebtXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.SecLoansDebtXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> SecLoansDebtAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.SecLoansDebtAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> MBAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.MBAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FlikvidAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.FlikvidAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> FlikvidXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FlikvidXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> LoansGoldXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.LoansGoldXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> LoansGoldAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.LoansGoldAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> DirRepoAuctionParamAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.DirRepoAuctionParamAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DirRepoAuctionParamXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.DirRepoAuctionParamXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<string[]> LombardListDatesAsync()
        {
            return base.Channel.LombardListDatesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> LombardListAsync(string dt)
        {
            return base.Channel.LombardListAsync(dt);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GCurveParamsAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.GCurveParamsAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IsotermAsync(System.DateTime OnDate, System.DateTime ToDate, int I_Day)
        {
            return base.Channel.IsotermAsync(OnDate, ToDate, I_Day);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GCurveAsync(System.DateTime OnDate)
        {
            return base.Channel.GCurveAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketCreditXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.NonMarketCreditXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketCreditAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.NonMarketCreditAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketAuctionParamAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.NonMarketAuctionParamAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketAuctionParamXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.NonMarketAuctionParamXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> NonMarketAuctionResultsAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.NonMarketAuctionResultsAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> NonMarketAuctionResultsXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.NonMarketAuctionResultsXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard3mXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard3mXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard6mXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard6mXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard1wXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard1wXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard2wXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard2wXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> rates_lombard12mXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard12mXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard3mAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard3mAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard6mAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard6mAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard12mAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard12mAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard1wAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard1wAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> rates_lombard2wAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.rates_lombard2wAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> FixedStav1DayXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FixedStav1DayXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> FixedStav7DayXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FixedStav7DayXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> FixedStav30DayXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FixedStav30DayXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FixedStav30DayAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FixedStav30DayAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FixedStav7DayAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FixedStav7DayAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> FixedStav1DayAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.FixedStav1DayAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ItogiDepoAuctXMLAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.ItogiDepoAuctXMLAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> ItogiDepoAuctAsync(System.DateTime OnDate, System.DateTime ToDate)
        {
            return base.Channel.ItogiDepoAuctAsync(OnDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IDRepoXMLAsync(System.DateTime OnDate)
        {
            return base.Channel.IDRepoXMLAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IDRepoAsync(System.DateTime OnDate)
        {
            return base.Channel.IDRepoAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IDRepoRUBXMLAsync(System.DateTime OnDate)
        {
            return base.Channel.IDRepoRUBXMLAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IDRepoRUBAsync(System.DateTime OnDate)
        {
            return base.Channel.IDRepoRUBAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IDRepoUSDXMLAsync(System.DateTime OnDate)
        {
            return base.Channel.IDRepoUSDXMLAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IDRepoUSDAsync(System.DateTime OnDate)
        {
            return base.Channel.IDRepoUSDAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> IBMRepoAsync(System.DateTime OnDate)
        {
            return base.Channel.IBMRepoAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IBMRepoXMLAsync(System.DateTime OnDate)
        {
            return base.Channel.IBMRepoXMLAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GKOOFZ_MR_XMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.GKOOFZ_MR_XMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> GKOOFZ_MRAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.GKOOFZ_MRAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Repo_sheduleFXAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.Repo_sheduleFXAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> REPOFXXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.REPOFXXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> REPOFXAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.REPOFXAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> REPOXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.REPOXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> REPOAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.REPOAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> OBRXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.OBRXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> OBRAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.OBRAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> MosPrimeXMLAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.MosPrimeXMLAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> MosPrimeAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.MosPrimeAsync(DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> BankPapersXMLAsync(System.DateTime OnDate)
        {
            return base.Channel.BankPapersXMLAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> BankPapersAsync(System.DateTime OnDate)
        {
            return base.Channel.BankPapersAsync(OnDate);
        }
        
        public System.Threading.Tasks.Task<CBR.Sec.ArrayOfXElement> CouponsAsync(System.DateTime DateFrom, System.DateTime DateTo)
        {
            return base.Channel.CouponsAsync(DateFrom, DateTo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecInfoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SecInfoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecInfoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cbr.ru/secinfo/secinfo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SecInfoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cbr.ru/secinfo/secinfo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SecInfoSoap,
            
            SecInfoSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
