name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use .NET 5.0.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
        
      - name: Building
        run: |
          dotnet build MathCore.DSP --nologo -c Release
          dotnet build Tests/MathCore.DSP.Tests --nologo -c Release
          
      - name: Run Tests
        run: dotnet test Tests/MathCore.DSP.Tests --no-build -c Release
        
      - name: Packing
        run: dotnet pack MathCore.DSP -c Release
        
      - name: Publishing
        run: dotnet nuget push MathCore.DSP/bin/Release/*.nupkg -k ${{ secrets.NuGetApiKey }} -n --skip-duplicate -s https://api.nuget.org/v3/index.json
