name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use .NET 3.1.200
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
        
      - name: Building
        run: dotnet build          
          
      - name: Testing
        run: dotnet test
        
      - name: Packing
        run: dotnet pack -c Release
        
      - name: Publishing
        run: dotnet nuget push MathCore.DSP/bin/Release/*.nupkg -k ${{ secrets.NuGetApiKey }} -n --skip-duplicate -s https://api.nuget.org/v3/index.json
