name: ASP.NET Core CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  test:
    name: Test on .NET Core for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use .NET 3.0.100-preview8-013656
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656
    - name: dotnet build and test
      run: |
        dotnet build --nologo --configuration Debug
        dotnet test --nologo
        
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656
    - name: Build with dotnet
      run: dotnet build --nologo --configuration Release
