name: Testing

on:
  push:
    branches: 
    - '*'
    paths-ignore: 
    - '.github/workflows/**'
    - '**.md'
    - '**.docx'
    - '**.bat'
    - '**.vssettings'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Cache NuGet  
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
          
      - name: Building
        run: |
          dotnet build MathCore.DSP -c Debug
          dotnet build Tests/MathCore.DSP.Tests -c Debug
          
      - name: Run Tests
        run: dotnet test Tests/MathCore.DSP.Tests --no-build -c Debug
