name: Testing

on: [push]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Building
        run: |
          dotnet build MathCore.DSP --nologo -c Debug
          dotnet build Tests/MathCore.DSP.Tests --nologo -c Debug
          
      - name: Run Tests
        run: dotnet test Tests/MathCore.DSP.Tests --no-build -c Debug
