name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test on .NET Core for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Use .NET 3.0.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
          
      - name: Building
        run: dotnet build --nologo --configuration Debug
          
      - name: Run Tests
        run: dotnet test --nologo
